Brmp 10002 9415
PSHCDevOps/discovery pull request #1142
Opened 2021-01-25 19:41 UTC by pramodganore

2021-01-25 19:44 UTC, chinchalinchin approved these changes

2021-01-25 20:16 UTC, theodesta requested changes

2021-01-25 20:16 UTC, theodesta commented on app/frontend/src/app/pages/contract-vehicles/erm.component.html
> +        Administration (NARA) worked together to develop <a href="https://www.archives.gov/records-mgmt/policy/universalermrequirements" target="_blank" aria-label="Universal Electronic Records Manag
External links might require another tag inside the <a href - otherwise Netsparker will trigger a vulnerability.  I can find out the exact tag if you like

2021-01-25 23:07 UTC, pramodganore commented on app/frontend/src/app/pages/contract-vehicles/erm.component.html
> +        Administration (NARA) worked together to develop <a href="https://www.archives.gov/records-mgmt/policy/universalermrequirements" target="_blank" aria-label="Universal Electronic Records Manag
@theodesta, i think the aria label doubles as a title, this was an existing implementation for the "about the ERM" page. Guessing we had squashed all NetSparker Vulnerabilities for Discovery already. Going with that gut feeling for now.

2021-01-26 12:37 UTC, sarim-hussain approved these changes

2021-01-26 14:15 UTC, dsomalaraju approved these changes

2021-01-26 14:15 UTC, merged